### ISSUE TITLE
Enable https using netlfiy

### ISSUE THREAD

**Issue by at15** [gaocegege/Blog#9]
Netlify provides https using let's encrypt 

- create dns zone in netlify
- point your dns server to netlify's dns servers in your domain name provider
- redirect http traffic to https using `_redirects`, or you can chose to force https

Ref

- https://github.com/at15/at15.github.io/issues/11

**Comment by at15** [comment]
and github also added support for https https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ cc @gaocegege 

你无视我的 issue 我要打咩了

**Comment by gaocegege** [comment]
Yeah. I know but I have no time to do it.

**Comment by at15** [comment]
Close as won't fix /w\
